//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Méphistophélès.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Méphistophélès.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap breaking_or {
            get {
                object obj = ResourceManager.GetObject("breaking-or", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cain {
            get {
                object obj = ResourceManager.GetObject("cain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cto {
            get {
                object obj = ResourceManager.GetObject("cto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        /// </summary>
        public static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap nto {
            get {
                object obj = ResourceManager.GetObject("nto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -----BEGIN CERTIFICATE-----
        ///MIIEKTCCAxGgAwIBAgIUXIwVzez02reK7mKBRRPqR2eWlUowDQYJKoZIhvcNAQEL
        ///BQAwfDELMAkGA1UEBhMCRlIxCzAJBgNVBAgMAk5ZMREwDwYDVQQHDAhOZXcgWW9y
        ///azEVMBMGA1UECgwMRXhhbXBsZSwgTExDMRUwEwYDVQQDDAwxOTIuMTY4LjEuNTgx
        ///HzAdBgkqhkiG9w0BCQEWEHRlc3RAZXhhbXBsZS5jb20wHhcNMjAwNjI0MTY1MTQy
        ///WhcNMjEwNjI0MTY1MTQyWjB8MQswCQYDVQQGEwJGUjELMAkGA1UECAwCTlkxETAP
        ///BgNVBAcMCE5ldyBZb3JrMRUwEwYDVQQKDAxFeGFtcGxlLCBMTEMxFTATBgNVBAMM
        ///DDE5Mi4xNjguMS41ODEfMB0GCSqGSIb3DQEJARYQdGVzdEBleGFtcGxlLmNvbTCC
        ///ASIwDQYJKoZIhvcNAQEBB [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string server_crt {
            get {
                return ResourceManager.GetString("server-crt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -----BEGIN PRIVATE KEY-----
        ///MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDRa7mRYnQH7YAg
        ///NRy6CuunOcQzfIFJ40PzNntahajX+QuukajHjJaOwtRkottsHY2Apf16E/4LrRpJ
        ///RR5FL/EjJH0aF+KBS55JEa7OJo3Bg7X+mF0Bvr1gcNbl3sdVp2VWJ1S1ZAM1S72k
        ///+SAgM6Q45olnIContIH643UgiNkNH/hRFE6LpFQSTIP7gn6tmykkztK19S7R/q6B
        ///YI+QqqnIJSIIac21bS3YVmFDZaNeuzU2fVlwO4Kqu1RhhGjLvnvaJC4iemqHnvMn
        ///vgOM8FulfZCD3loHdJYBCWIYR0sKapsENT3lTt8Jo33qZxmllbszhyeBov1OUbvR
        ///OBlUGepNAgMBAAECggEBALTY1VhycAcElze5BgS3N4eiwAdCRpgbFWvrqZyjfgp7
        ////BWVne4tPzsrjqUVam00H [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string server_key {
            get {
                return ResourceManager.GetString("server-key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à from http.server import HTTPServer, BaseHTTPRequestHandler
        ///import ssl,configparser
        ///
        ///port = #port
        ///
        ///authresponse = &quot;#auth&quot;
        ///
        ///class SimpleHTTPRequestHandler(BaseHTTPRequestHandler):
        ///
        ///	def do_GET(self):
        ///		self.send_response(200)
        ///		self.end_headers()
        ///		self.wfile.write(bytes(authresponse,&quot;utf-8&quot;))
        ///		exit(0)
        ///
        ///	def do_POST(self):
        ///		self.send_response(200)
        ///		self.end_headers()
        ///		self.wfile.write(bytes(authresponse,&quot;utf-8&quot;))
        ///		exit(0)
        ///
        ///httpd = HTTPServer((&apos;127.0.0.1&apos;,port),SimpleHTTPRequestHandle [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string Server_Source {
            get {
                return ResourceManager.GetString("Server-Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à using System;
        ///using System.Text;
        ///using System.Diagnostics;
        ///using System.IO;
        ///using System.Threading;
        ///
        ///namespace Mephistopheles
        ///{
        ///    static class Source
        ///    {
        ///        public static string server_link = &quot;#server&quot;;
        ///
        ///        /// &lt;summary&gt;
        ///        /// Point d&apos;entrée principal de l&apos;application.
        ///        /// &lt;/summary&gt;
        ///        [STAThread]
        ///        static void Main(string[] args)
        ///        {
        ///            string server = &quot;C:\\Windows\\System32\\drivers\\etc\\hosts&quot;;
        ///
        ///            File.AppendAllText(ser [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
    }
}
